export const fonts = [
  'Arial',
  'Times New Roman',
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Raleway',
  'Oswald',
  'Playfair Display',
  'Merriweather',
  'Source Sans Pro',
  'PT Sans',
  'Nunito',
  'Ubuntu',
  'Poppins',
  'Quicksand',
  'Pacifico',
  'Dancing Script',
  'Great Vibes',
  'Satisfy',
  'Lobster',
  'Sacramento',
  'Courgette',
  'Kaushan Script',
  'Yellowtail',
  'Allura',
  'Alex Brush',
  'Pinyon Script',
  'Mr De Haviland',
  'Tangerine',
  'Petit Formal Script',
  'Cinzel',
  'Philosopher',
  'Crimson Text',
  'Libre Baskerville',
  'Josefin Sans',
  'Abril Fatface',
  'Righteous',
  'Concert One',
  'Fredoka One'
];